name: Retrieve Data, Execute Model, and Deploy Website

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master
  schedule:
    - cron: "30 * * * *"

env:
  CACHE_NUMBER: 0

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Sets up environment for running the model (with caching)
  # See (https://dev.to/epassaro/caching-anaconda-environments-in-github-actions-5hde)
  
  build:
    runs-on: 
      - os: ubuntu-latest
        prefix: "usr/share/miniconda3/envs/my-env"
    
    name: Setup Mambaforge
    steps:
      - uses: actions/checkout@v2


