name: Retrieve Data, Execute Model, and Deploy Website

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "30 * * * *"

env:
  CACHE_NUMBER: 0

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Sets up environment for running the model (with caching)
  # See (https://dev.to/epassaro/caching-anaconda-environments-in-github-actions-5hde)
  
  build:
    runs-on: ubuntu-latest 
    name: Full Pipeline
    strategy:
      max-parallel: 1
    
    defaults:
      run:
        shell: bash -l {0}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
    
      - name: Setup Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: latest
          environment-file: envs/environment.yaml
          log-level: debug
          init-shell: bash
          cache-environment: true
          cache-downloads: true
      
      - name: Set cache dates
        run: |
          echo "WEEK=$(date +'%Y%U')" >> $GITHUB_ENV
      
      - name: Print environment
        run: conda list --explicit > actions_environment.txt
      
      - name: Show current env
        run: conda list
      
      - name: Show currently available envs
        run: conda env list
      
      - name: Activate environment
        run: micromamba activate pypsa-eur

      - name: Run Python script
        run:
          conda info --envs
          
          python scripts/solve_network.py
      
      - name: Set up Git config
        run: |
          git config --global user.name "LukasFrankenQ"
          git config --global user.email "lukas.franken@ed.ac.uk"

      - name: Commit and push environment
        run: |
          git add .
          git commit -m "Update actions_environment.txt and random numbers" -a || echo "No changes to commit"
          git push git@github.com:${{ github.repository }}.git HEAD:main