name: Retrieve Data, Execute Model, and Deploy Website

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "30 * * * *"

env:
  CACHE_NUMBER: 0

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Sets up environment for running the model (with caching)
  # See (https://dev.to/epassaro/caching-anaconda-environments-in-github-actions-5hde)
  
  build:
    runs-on: ubuntu-latest 
    name: Setup Mambaforge
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
            miniforge-variant: Mambaforge
            miniforge-version: latest
            activate-environment: pypsa-eur
            use-mamba: true
      
      - name: Set cache date
        run: echo "DATE=$(date +%Y%m%d)" >> $GITHUB_ENV
      
      - uses: actions/cache@v2
        with:
          path: /envs/
          key: ubuntu-conda-${{ hashFiles('envs/environment.yaml') }}-${{ env.DATE }}-${{ env.CACHE_NUMBER }}
        id: cache
      
      - name: Update environment
        run: mamba env update -n pypsa-eur -f envs/environment.yaml
        if: steps.cache.outputs.cache-hit != 'true'